Repository AY2021S2-CS2103T-W15-1/tp, pull requests merged in 2021-04, with the labels that each got.

#239 Fix birthday display in EventList
  src/main/java/seedu/address/model/EventList.java
Labels: type.bugfix

#242 Change display String for generalEvent and CalendarWindow
  src/main/java/seedu/address/model/EventList.java
  src/main/java/seedu/address/model/event/GeneralEvent.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/ui/calendar/schedule/CalendarEventCard.java
Labels: type.bugfix

#232 Add tests for JsonAdapted classes
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/test/data/JsonSerializableRemindMeTest/duplicateEventRemindMe.json
  src/test/data/JsonSerializableRemindMeTest/duplicateModuleRemindMe.json
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExamTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGeneralEventTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonSerializableRemindMeTest.java
  src/test/java/seedu/address/testutil/TypicalRemindMe.java
Labels: type.test

#302 Fix switching of tabs after every command
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.bugfix

#303 Add missing index for modules
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
Labels: type.bugfix

#304 Fix Ui display of done status
  src/main/java/seedu/address/logic/commands/ToggleDoneAssignmentCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RemindMe.java
  src/test/java/seedu/address/logic/commands/addcommand/AddPersonCommandTest.java
Labels: type.bugfix

#306 Fix display issue of edit exam
  src/main/java/seedu/address/model/RemindMe.java
  src/test/java/seedu/address/logic/commands/editcommand/EditExamCommandTest.java
Labels: type.bugfix

#307 Fix bugs in DeleteExam and DeleteAssignment to allow immediate updating of UI
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteAssignmentCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteExamCommand.java
  src/main/java/seedu/address/model/RemindMe.java
Labels: type.bugfix

#308 Update UG intro
  docs/UserGuide.md
Labels: documentation

#313 Add EditEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditEventCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditPersonCommandParserTest.java
Labels: type.test

#314 Add EditModuleCommandParserTest.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditEventCommandParserTest.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditModuleCommandParserTest.java
Labels: type.test

#319 Add EditExamCommandParserTest.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditExamCommandParser.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditExamCommandParserTest.java
Labels: type.test

#320 Add EditAssignmentCommandParserTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditAssignmentCommandParserTest.java
Labels: type.test

#321 Update UG intro
  docs/UserGuide.md
Labels: documentation

#323 Add EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditCommandParserTest.java
Labels: type.test

#332 Update DG Design and Implementation diagrams and explanations
  docs/DeveloperGuide.md
  docs/diagrams/EditFeatureActivityDiagram.puml
  docs/diagrams/EditFeatureSequenceDiagram.puml
  docs/diagrams/EditFeatureSequenceDiagram1.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/EditFeatureActivityDiagram.png
  docs/images/EditFeatureSequenceDiagram.png
  docs/images/EditFeatureSequenceDiagram1.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/cards/EventCard.java
  src/main/java/seedu/address/ui/cards/ModuleCard.java
  src/main/java/seedu/address/ui/cards/PersonCard.java
  src/main/java/seedu/address/ui/panels/DisplayPanel.java
  src/main/java/seedu/address/ui/panels/EventListPanel.java
  src/main/java/seedu/address/ui/panels/ModuleListPanel.java
  src/main/java/seedu/address/ui/panels/PersonListPanel.java
Labels: documentation

#333 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation

#334 Minor wording changes to UserGuide v1.4
  docs/UserGuide.md
Labels: documentation

#335 Reformat warning boxes in UserGuide v1.4
  docs/UserGuide.md
Labels: documentation

#336 Add additional linebreaks in warning boxes for UserGuide v1.4
  docs/UserGuide.md
Labels: documentation

#337 Update hzxin PPP
  docs/team/hzxin.md
Labels: documentation

#338 Update README.md
  README.md
Labels: documentation

#339 Fix spacing
  README.md
Labels: documentation

#347 Replace Calendar UG images with correct result display
  docs/UserGuide.md
  docs/images/Calendar3.png
  docs/images/calendar1.png
  docs/images/calendar2.png
  docs/images/calendar3.png
Labels: documentation, type.bugfix

#348 Update jellymias.md
  docs/team/jellymias.md
Labels: documentation

#353 Fix hyperlinks and add diagram notations in DG
  docs/DeveloperGuide.md
Labels: documentation

#354 Update diagrams and links in index.md
  README.md
  docs/index.md
Labels: documentation

#355 Fix format of PPP
  docs/team/hzxin.md
Labels: documentation

#356 Fix table of contents in DG
  docs/DeveloperGuide.md
Labels: documentation, type.bugfix

#357 Update UG images and notations
  docs/UserGuide.md
  docs/images/calendar3.png
Labels: documentation, type.bugfix

#359 Add AddFeatureActivityDiagram
  docs/DeveloperGuide.md
  docs/diagrams/AddFeatureActivityDiagram.puml
  docs/images/AddFeatureActivityDiagram.png
Labels: documentation

#360 Update Add Feature in DG
  docs/DeveloperGuide.md
Labels: documentation

#373 Bugfix birthday display
  src/main/java/seedu/address/commons/util/LocalDateTimeUtil.java
  src/main/java/seedu/address/model/module/Assignment.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.bugfix

#377 Update reused code
  src/main/java/seedu/address/commons/util/LocalDateTimeUtil.java
  src/main/java/seedu/address/ui/panels/DisplayPanel.java
  src/main/resources/view/DisplayPanel.fxml
  src/main/resources/view/customizedStyle/CustomizedTheme.css
Labels: documentation

#378 update reuse code v1.1
  src/main/java/seedu/address/ui/calendar/CalendarBox.java
Labels: documentation
