Repository AY2021S2-CS2103T-W15-1/tp, pull requests merged in 2021-03, with the labels that each got.

#51 Update website
  docs/_config.yml
Labels: documentation

#52 Update index.md
  docs/index.md
Labels: documentation

#47 Integrate ug v1.1
  docs/UserGuide.md
  docs/images/Reminder.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: documentation

#60 Implement calendarCommand and Calendar UI
  src/main/java/seedu/address/logic/commands/CalendarCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CalendarBox.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarBox.fxml
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.feature

#68 Implement calendar
  src/main/java/seedu/address/logic/commands/CalendarCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CalendarBox.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CalendarBox.fxml
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Ui, type.feature

#101 Skeleton of remidner-window
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/background.png
  src/main/resources/images/logoCalligraphy.png
  src/main/resources/view/ReminderWindow.fxml
Labels: type.feature

#124 Synk reminder pop-up with storage
  src/main/java/seedu/address/model/EventList.java
  src/main/java/seedu/address/ui/ReminderWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow2.fxml
  src/main/resources/view/ReminderWindow.fxml
Labels: type.Ui, type.feature

#127 Adjust toString andimprove Mainwindow Ui
  src/main/java/seedu/address/model/module/Assignment.java
  src/main/java/seedu/address/model/module/AssignmentList.java
  src/main/java/seedu/address/model/module/ExamList.java
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DisplayPanel.fxml
  src/main/resources/view/MainWindow2.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/customizedStyle/CustomisedExtensions.css
  src/main/resources/view/customizedStyle/CustomizedTheme.css
Labels: type.Ui

#148 increase main-window size
  build.gradle
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/resources/view/MainWindow2.fxml
Labels: type.Ui

#149 Adjust PersonPanel and include birthday in GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DisplayPanel.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/customizedStyle/CustomisedExtensions.css
  src/main/resources/view/customizedStyle/CustomizedTheme.css
Labels: type.Ui

#150 Modify reminder window
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/ui/ReminderWindow.java
  src/main/resources/images/reminderwindowbackground.png
  src/main/resources/view/MainWindow2.fxml
  src/main/resources/view/ReminderWindow.fxml
  src/main/resources/view/customizedStyle/transparentTheme.css
Labels: type.Ui

#151 provide space-free tag for Events
  src/main/java/seedu/address/logic/parser/addcommandparser/AddAssignmentCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddExamCommandParser.java
Labels: type.bugfix

#157 Implement adaptedAssignment/Exam test
  src/main/java/seedu/address/commons/util/LocalDateTimeUtil.java
  src/main/java/seedu/address/model/event/GeneralEvent.java
  src/main/java/seedu/address/model/module/Assignment.java
  src/main/java/seedu/address/model/module/Description.java
  src/main/java/seedu/address/model/module/Exam.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExamTest.java
  src/test/java/seedu/address/testutil/TypicalRemindMe.java
Labels: type.test

#162 Integrate general event GUI
  src/main/java/seedu/address/model/Event.java
  src/main/java/seedu/address/ui/DisplayPanel.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/resources/view/DisplayPanel.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/EventListPanel.fxml
Labels: type.Ui

#166 Draft UserGuide v1.3
  docs/UserGuide.md
  docs/UserGuideNew.md
  docs/images/Ui.png
  docs/images/UiMainWindow.png
Labels: documentation

#187 Update DG Edit-feature implementation with puml diagrams
  docs/DeveloperGuide.md
  docs/diagrams/EditFeatureActivityDiagram.puml
  docs/diagrams/EditFeatureClassDiagram.puml
  docs/diagrams/EditFeatureSequenceDiagram.puml
  docs/images/EditFeatureActivityDiagram.png
  docs/images/EditFeatureClassDiagram.png
  docs/images/EditFeatureSequenceDiagram.png
Labels: documentation

#192 Update DG Add feature
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandParserClassDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddCommandParserClassDiagram.png
  docs/images/AddSequenceDiagram.png
Labels: documentation

#194 Integration of UG
  docs/UserGuide.md
  docs/UserGuideNew.md
Labels: documentation

#195 Make new RemindMe Diagrams and update contents in DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#196 Syntax fix for DG v0.1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: documentation

#197 Syntax fix for DG v0.2
  docs/DeveloperGuide.md
Labels: documentation

#202 Add SchedulePanelPLaceHolder in CalendarWindow
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/calendar/CalendarWindow.java
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/customizedStyle/CustomizedTheme.css
Labels: type.Ui

#203 Implement storage for doneStatus
  src/main/java/seedu/address/model/module/Assignment.java
  src/main/java/seedu/address/storage/JsonAdaptedAssignment.java
  src/test/java/seedu/address/storage/JsonAdaptedAssignmentTest.java
Labels: type.feature

#212 Change UG command summary and format
  docs/UserGuide.md
Labels: documentation

#213 Update UG format and image size
  docs/UserGuide.md
  docs/images/Ui2.png
  docs/images/UiMainWindow.png
Labels: documentation

#219 Modify MainWindowUi theme
  src/main/resources/view/customizedStyle/CustomisedExtensions.css
  src/main/resources/view/customizedStyle/CustomizedTheme.css
Labels: type.Ui

#220 Add EditAssignmentCommandTest.java
  src/main/java/seedu/address/logic/commands/editcommand/EditAssignmentCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/editcommand/EditAssignmentCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalRemindMe.java
Labels: type.test

#221 Add EditExamCommandTest.java
  src/main/java/seedu/address/logic/commands/editcommand/EditExamCommand.java
  src/test/java/seedu/address/logic/commands/editcommand/EditAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditExamCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalRemindMe.java
Labels: type.test

#224 Fix filterList not updated Bug
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/DisplayPanel.java
Labels: type.bugfix

#231 Add EditEventCommandTest.java
  src/main/java/seedu/address/logic/commands/editcommand/EditEventCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/addcommand/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditEventCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedGeneralEventTest.java
  src/test/java/seedu/address/testutil/GeneralEventBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalRemindMe.java
Labels: type.test
